#!/usr/bin/env bash
#This will redirect permanently
sudo apt -y update
sudo apt -y install nginx
echo "Ceci n'est pas une page" >> /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" >> /usr/share/nginx/html/custom_404.html
custom_404="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "39i $custom_404" /etc/nginx/sites-enabled/default
sudo service nginx restart
