#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
apt update
apt install haproxy
cat >> /etc/haproxy/haproxy.cfg << EOF
listen www
        bind :80
        mode http
        server 1719-web-01 44.200.64.248
        server 1719-web-02 44.210.151.93
EOF
service haproxy start
