#!/usr/bin/env bash
# Prints "Best School" 10 times using while loop, but prints bad luck on the
# 4th iteration, good luck on the 8th iteration

i=1

while [ $i -le 10 ]
do
  if [ $i == 4 ]
  then
      echo "bad luck"

  elif [ $i == 8 ]
  then
      echo "good luck"
  else

  echo "Best School"
  fi
  ((i++))
done