#!/usr/bin/env bash
# Prints "Best School" 10 times using while loop, but prints bad luck on the
# 4th iteration, good luck on the 8th iteration

i=1

while [ $i -le 20 ]
do
  echo $i;

  case $i in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  ((i++))
done
