#!/usr/bin/env bash
# running nginx with user nginx

chown nginx:nginx /etc/nginx/nginx.conf
chmod 664 /etc/nginx/sites-available/default
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
